
[game]
name = "Threads of Fate"
id = "SLUS-01019"
players = 1
exe = "disc/SLUS_010.19"
disc = "disc/Threads of Fate (USA, Canada).cue"
discs = ["disc/Threads of Fate (USA, Canada).cue"]
disc_serials = ["SLUS-01019"]
load_address = "0x80010004"
entry_pc = "0x8003FDD8"
text_size = "0x00097800"
stack_base = "0x801FFFF0"

[prepare_disc]
out_dir = "disc"
bin_name = "Threads of Fate (USA, Canada).bin"
cue_name = "Threads of Fate (USA, Canada).cue"
boot_exe = "SLUS_010.19"
known_sizes = [357454608]
known_md5 = ["bf49e5e7a09acc46625b5ced33dd45f5"]
known_sha1 = ["375e4a344c4feef969bef6042ff1f90e350fa5d5"]
known_crc32 = ["59b2f8a3"]

[recompiler]
bios_config = "psxrecomp/bios/SCPH1001.toml"
seeds = "seeds/ghidra_funcs.txt"
out_dir = "generated"
strict = true

[runtime]
window_title = "Threads of Fate Recompiled"
memcard_dir = "saves"
openbios = false

[video]
renderer = "opengl"
aspect_ratio = "4:3"

[controller]
default_mode = "digital"

[netplay]
require_cue = true
required_tracks = 1
required_disc_fp = "96509f6935040fd69c3d2838f6de3a91db5b614cfdbf8765bbcc3cca2c2e317b"
